version: '2'
services: 
  webapi:
    build: ./WebAPI   
    container_name: "webapi" 
    command: yarn start
    ports:
      - "3000:3000"
    links:
        - mongodb
    depends_on:
        - mongodb
        
  webclient:
    container_name: "webclient"
    build: ./WebClient
    command: yarn start
    ports: 
      - "3001:3001"
    links:
      - webapi
    depends_on:
      - webapi
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null 