version: "3"

networks:
  twitter_network:
    driver: bridge

services:
  twitter_api:
    build:
      context: ./api/
      dockerfile: dockerFile
    container_name: "twitter_api"
    env_file:
      - .env
    ports:
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - twitter_network

  twitter_app:
    build:
      context: ./frontend/twitter/
      dockerfile: dockerFile
    container_name: "twitter_app"
    env_file:
      - .env
    ports:
      - "3000:3000"
    links:
      - twitter_api
    depends_on:
      - twitter_api
    networks:
      - twitter_network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - twitter_network
