version: "3"

networks:
  twitter-network:
    driver: bridge

services:
  twitter_api:
    build:
      context: ./api/
      dockerfile: dockerFile
    container_name: "twitter_api"
    env_file:
      - .env
    ports:
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - twitter-network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - twitter-network
