version: "3"

networks:
    twitter-network:
        driver: bridge

services:

  twitter_api:
    build: ./api
    container_name: "twitter_api"
    ports:
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks: 
      - twitter-network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    networks: 
      - twitter-network
